name = "hamzehi-social-ai"
main = "src/index.js"
compatibility_date = "2026-09-11"

[triggers]
crons = ["0 7 * * *", "*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_id = "40b272c5-e368-4c33-8a41-7c63db98d7e8"

[ai]
binding = "AI"

[vars]
RATE_LIMIT_PER_MINUTE = "60"
